### ISSUE TITLE
Escaped forward slash followed by "n" does not unescape properly.

### ISSUE THREAD

**Issue by RoboPhred** [jpoehls/vscode-json-escaper#1]
The json string
```
"{\"foo\": \"bar\\ninja\"}"
```

Improperly unescapes to
```
"{"foo": "bar\
inja"}"
```

The issue seems to be that
unescapeJsonString()
will look for \n before \\.  However, exchanging the order will just break it in the other direction.
The solution is probably to use a general purpose, singular "backslash+anything" replace regex with a replacer function to check what character followed the backslash and replaces the pair appropriately.  This would eliminate the double-matching issue.

**Comment by jpoehls** [comment]
This is fixed in the v1.1.0 release that I just published. Let me know if you run into any other issues. Thanks!
