### ISSUE TITLE
How do you use it?

### ISSUE THREAD

**Issue by twocs** [jpoehls/vscode-json-escaper#3]
This extension only says that it "adds commands". What is the simple way to use it? Do I right click in a document? Do I need to convert the document to JSON first? Are the commands available only through Ctrl +

**Comment by jpoehls** [comment]
The extension adds two commands. You can access them via the Command Palette.

https://github.com/jpoehls/vscode-json-escaper/blob/142f3c902abc4efe6fe14c0e087a52813a91edbf/src/extension.ts#L12-L15

My usual workflow is to select the snippet of text I want to operate on, and then run the command I want using the Command Palette.
